AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Organizes all the emails that come in.
Resources:
  Inbound:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      MemorySize: 128
      Runtime: nodejs10.x
      Timeout: 3
